---
  - name: Install and configure tomcat
    hosts: web
    gather_facts: false
    vars:
      java_version: java-1.8.0-openjdk
      set_java: jre-1.8.0-openjdk
      tomcat_version: 9.0.63
      tomcat_url: https://dlcdn.apache.org/tomcat/tomcat-{{tomcat_version.split('.')[0]}}/v{{tomcat_version}}/bin/apache-tomcat-{{tomcat_version}}.tar.gz
    become: yes
    tasks:
      - name: Updating repos
        yum:
          name: "*"
          state: latest
      - name: Installing required java
        yum:
          name: "{{java_version}}"
          state: present
      - name: Setting default java
        alternatives:
          name: java
          link: /usr/bin/java
          path: /usr/lib/jvm/{{set_java}}/bin/java
      - name: Downloading Tomcat
        get_url:
          url: "{{tomcat_url}}"
          dest: /usr/local
      - name: Extracting tomcat
        unarchive:
          src: "/usr/local/apache-tomcat-{{tomcat_version}}.tar.gz"
          dest: /usr/local
          remote_src: yes
      - name: Removing previous tomcat folder
        command: rm -rf /usr/local/latest
      - name: Renaming tomcat folder
        command: mv /usr/local/apache-tomcat-{{tomcat_version}} /usr/local/latest
      - name: Starting tomcat
        shell: nohup /usr/local/latest/bin/startup.sh &
